# Generated by Django 5.2.5 on 2025-08-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=50, verbose_name='اسم الخصم')),
                ('pgn_content', models.TextField(verbose_name='محتوى PGN')),
                ('result', models.CharField(choices=[('1-0', 'فوز الأبيض'), ('0-1', 'فوز الأسود'), ('1/2-1/2', 'تعادل')], max_length=7, verbose_name='النتيجة')),
                ('date_played', models.DateField(verbose_name='تاريخ اللعب')),
                ('time_control', models.CharField(blank=True, max_length=20, verbose_name='زمن التحكم')),
                ('player_color', models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود')], max_length=5, verbose_name='لون اللاعب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المباريات',
                'unique_together': {('player', 'opponent_name', 'date_played')},
            },
        ),
    ]
