# Generated by Django 5.2.5 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0002_playerstats_openingstat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('player', 'opponent_name', 'date_played', 'time_control')},
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.URLField(blank=True, verbose_name='رابط المباراة'),
        ),
        migrations.AddField(
            model_name='game',
            name='moves_count',
            field=models.IntegerField(default=0, verbose_name='عدد النقلات'),
        ),
        migrations.AddField(
            model_name='game',
            name='opening_eco',
            field=models.CharField(blank=True, max_length=3, verbose_name='رمز ECO'),
        ),
        migrations.AddField(
            model_name='game',
            name='opening_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الافتتاح'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='تصنيف الخصم'),
        ),
    ]
