# Generated by Django 5.2.5 on 2025-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='اسم المستخدم')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الكامل')),
                ('country', models.CharField(default='DZ', max_length=2, verbose_name='البلد')),
                ('current_rating', models.IntegerField(blank=True, null=True, verbose_name='التصنيف الحالي')),
                ('avatar_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
            },
        ),
    ]
