# Generated by Django 5.2.5 on 2025-08-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0, verbose_name='إجمالي المباريات')),
                ('wins', models.IntegerField(default=0, verbose_name='الانتصارات')),
                ('losses', models.IntegerField(default=0, verbose_name='الهزائم')),
                ('draws', models.IntegerField(default=0, verbose_name='التعادلات')),
                ('favorite_opening', models.CharField(blank=True, max_length=100, verbose_name='الافتتاح المفضل')),
                ('weakest_defense', models.CharField(blank=True, max_length=100, verbose_name='أضعف دفاع')),
                ('average_game_length', models.IntegerField(default=0, verbose_name='متوسط طول المباراة')),
                ('last_analysis', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحليل')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'إحصاءات لاعب',
                'verbose_name_plural': 'إحصاءات اللاعبين',
            },
        ),
        migrations.CreateModel(
            name='OpeningStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_name', models.CharField(max_length=100, verbose_name='اسم الافتتاح')),
                ('eco_code', models.CharField(max_length=3, verbose_name='رمز ECO')),
                ('games_played', models.IntegerField(default=0, verbose_name='المباريات الملعوبة')),
                ('wins', models.IntegerField(default=0, verbose_name='الانتصارات')),
                ('losses', models.IntegerField(default=0, verbose_name='الهزائم')),
                ('draws', models.IntegerField(default=0, verbose_name='التعادلات')),
                ('color_played', models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود'), ('both', 'كلاهما')], default='both', max_length=5, verbose_name='اللون المُلعب')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'إحصاءات افتتاح',
                'verbose_name_plural': 'إحصاءات الافتتاحات',
                'unique_together': {('player', 'opening_name', 'eco_code')},
            },
        ),
    ]
